sudo: false
language: python
python:
  - "3.8"
  - "3.9"
  - "nightly"
  - "pypy3"

install:
  - pip install -r dev-requirements.txt
  - "if [[ $HIREDIS == '1' ]]; then pip install hiredis; fi"
env:
  global:
    - IS_TRAVIS=1
  matrix:
    - HIREDIS=0
    - HIREDIS=1


script:
  - coverage erase
  - coverage run --source redpipe -p test.py
  - flake8 --exclude=./build,.venv*,.tox,dist
  - mypy redpipe test.py

after_success:
  - coverage combine
  - coveralls
matrix:
  allow_failures:
    - python: "nightly"
    - python: "pypy3"
  include:
    - python: 3.8
    - python: 3.9
      dist: xenial
      sudo: true
